Dev
Goldinium/Space_Travelers_Hub pull request #131
Opened 2023-10-13 19:59 UTC by Goldinium

#### Config & basic setup

- Created React App.
- Installed [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/articles/react_router.md).
- Download the [free image](https://www.flaticon.com/free-icon/planet_3212567?term=space&page=1&position=19&page=1&position=19&related_id=3212567&origin=style) for the app logo.
- Created **routes** and **view** components: `rockets`, `missions`, `my profile`.
  - Used `<NavLink />` for the page navigation links and style active class to indicate which section/page user is currently on (underline active navigation link).
- Created directories for all Redux state slice files:`rockets`, `missions`.

#### Redux: Fetch data and update Redux store

- Upon first render fetch data from the SpaceX API endpoints:
  - Rockets: `https://api.spacexdata.com/v4/rockets`
  - Missions: `https://api.spacexdata.com/v3/missions`
  - Dragons: `https://api.spacexdata.com/v4/dragons` _[only if your team has 3 members]_
- Once the data are fetched, dispatch an action to store the selected data in Redux store:
  - Rockets:
    - id
    - rocket_name
    - description
    - flickr_images
  - Missions:
    - mission_id
    - mission_name
    - description

Made sure to only dispatch those actions once and do not add data to store on every re-render (i.e. when changing views / using navigation).
_Rockets_ is the default view, we fetch _rockets_ data when the application starts. and, the _missions_ data should only be fetched (once) when a user navigates to the _Missions_ section.

#### Render UI:lists

- Used `useSelector()` Redux Hook to select the state slices and render lists of rockets and missions in corresponding routes. i.e.:

```javascript
// get rockets data from the store
const rockets = useSelector((state) => state.rockets)
```

- styled the whole application "by hand" .
- Render a list of rockets (as per design). For the image of a rocket use the first image in the array of `flickr_images`.
- Render a table with the missions' data (as per design).

#### Redux: Write actions and reducers for booking rockets/dragons and joining missions

- When a user clicks the "Reserve rocket" button , action are dispatched to update the store. 

-Made sure to place all the logic in the reducer. In the React view file, only dispatch the action with the correct rocket ID as an argument.
- Created a reducer and action dispatcher for the "Join Mission" button. The logic here is practically the same as with rockets.

#### Redux: Write actions and reducers for canceling rockets/dragons and leaving missions

-Followed the same logic as with the "Reserve rocket"/"Reserve dragon" and "Join mission" - but you need to set the `reserved` key to `false`.
- Dispatch these actions upon click on the corresponding buttons.

#### Render UI: conditional components rendering

- Rockets that have already been reserved should show a "Reserved" badge and "Cancel reservation" button instead of the default "Reserve rocket" (as per design) .
- Dragons that have already been reserved should show a "Reserved" badge and "Cancel reservation" button instead of the default "Reserve dragon" (as per design) _[only if your team has 3 members]_.
- Missions that the user has joined already should show a badge "Active Member" instead of the default "NOT A MEMBER" and a button "Leave Mission" instead of the "Join Mission" button (as per design).
- Rockets and Missions use the React conditional rendering syntax:

#### Render UI: My Profile section

- Composed two/three column layout and list ONLY the rockets/dragons reserved and missions joined by the user (as per design):
  - Rendered a list of all joined missions (use `filter()`).
  - Rendered a list of all reserved rockets (use `filter()`).
  - Rendered a list of all reserved dragons (use `filter()`) [only if your team has 3 members]\_.

#### Technical set up\*\*

- Set up the repository on GitHub and use Gitflow.
- Set up React and Redux.
- Set up testing libraries(React Testing Library and Jest).
- Did not preserve user data.

2023-10-13 22:22 UTC, prolajumokeoni requested changes
Hi @Goldinium and @ometman 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Design matches the wireframe 👍🏿 
- Data fetched from the SpaceX API endpoints ✅




## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 22:22 UTC, prolajumokeoni commented on src/components/Rocket.js
> +              Cancel Reservation
- [ ] It would be nice to give your button the same color with the color in the wireframe 👍🏿 




Wireframe Design          |  Your design     
:-------------------------:|:-------------------------:
<img width="1181" alt="space-travelers__rockets" src="https://github.com/Goldinium/Space_Travelers_Hub/assets/69638013/2aa834ac-cf57-4a37-bef1-2c7c08743b88">  |  ![Screenshot_202](https://github.com/Goldinium/Space_Travelers_Hub/assets/69638013/3e702ed1-8147-402e-89fa-0a59e31f4d62)

2023-10-14 05:48 UTC, Goldinium commented
@prolajumokeoni  requested  changes have been implemented

2023-10-14 06:12 UTC, peterrobert commented on src/routes/NavLink.js
> +          </ul>
This change has not yet been done.

2023-10-14 06:13 UTC, peterrobert commented on src/components/Rocket.js
> +              Cancel Reservation
This change has been done well

2023-10-14 06:16 UTC, peterrobert requested changes
Hi @Goldinium and @ometman , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-14 06:16 UTC, peterrobert commented on src/routes/NavLink.js
> +          </ul>
- [ ] It will be great to ensure that the active link is indicated by a line under it. What the first reviewer meant is that let's say you are on the profile page, on the nav link should indicate with a line under it that that is the active page. Kindly implement this change

2023-10-14 07:29 UTC, Felix45 approved these changes
# Approved :green_circle: 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
Hi @Goldinium & @ometman, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Application functions as expected :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] `Redux` is used to manage the state of the application :white_check_mark: 
- [x] Implemented changes from the previous reviewer :white_check_mark:    

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-14 07:39 UTC, merged